version: '3.8'

services:
  startracker:
    build: .
    command: ["./app", "start-node", "--log-level=info", "--config-path=config.yaml"]
    logging:
      driver: "json-file"
      options:
          max-file: 5
          max-size: 10m
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb
      - ./config/config.yaml:/app/config.yaml